statisticsnorway/dapla-toolbelt-metadata

src/dataset/statistic_subject_mapping.py

Added check for url not being null before trying to make a request to statistic subject structure

Added Null check for statistic subject url

---

docs/reference.md

Add content - not sure if this is 100% correct yet

Add content to docs

---

backstage.yaml

- **Add backstage.yaml**
- **Backstage: Add relationship to klass-api**

Backstage: Add relationship to klass-api

---

src/dapla_metadata/variable_definitions/exceptions.py
src/dapla_metadata/variable_definitions/variable_definition.py
tests/variable_definitions/conftest.py
tests/variable_definitions/resources/variable-definitions-0.1.yml
tests/variable_definitions/test_vardef.py

Methods:
- update_draft:
- delete_draft
- Custom response message when draft is deleted 
- create_patch
- create_validity_period
Add exception handler to get_patch
Docstrings can be improved

Add methods for variable owner

---

pyproject.toml

Fix coverage configuration

---

demo/datasets/create_metadata_for_new_dataset.ipynb
demo/datasets/create_metadata_for_new_period.ipynb
demo/variable_definitions/read_variable_definitions.ipynb
demo/variable_definitions/vardef_client_demo.ipynb

Remove Jupyter file changes. Should not have been pushed to git.

Strip Jupyter notebooks

---

.github/workflows/tests.yml

This reverts commit 98dd928d5d6780329bdd7809c213337f15bfa19b.
Seems like this commit caused another issue

Revert "update sonar scan because job is deprecated"

---

pyproject.toml
src/dapla_metadata/datasets/core.py

- Changing the output of the metadata document so that it can be interpreted as json in GCP
- Also releasing a new version

Changing the logging of the saved metadata document

---

.github/workflows/constraints.txt
.github/workflows/tests.yml
pyproject.toml

According to https://github.com/python-poetry/poetry-plugin-export this should be the correct way to solve the breaking change in Poetry 2.0

inject plugin in workflow

---

src/dapla_metadata/variable_definitions/exceptions.py
tests/variable_definitions/test_vardef.py
tests/variable_definitions/vardef_client/test_exceptions.py

Handle urllib3 exceptions

---

demo/variable_definitions/migrere_variabel_definisjon.ipynb
src/dapla_metadata/variable_definitions/vardef.py

- Added migration notbook
- Changed migration code to return a path to the saved draft variable

Added migration notebook

---

demo/variable_definitions/migrere_variabel_definisjon.ipynb
demo/variable_definitions/opprette_utkast.ipynb

- **remove blocks which are moved to another notebook**
- **Move block to align with other notebooks**

Ensure compliance notebooks

---

demo/variable_definitions/redigere_publisert_variabel_definisjon.ipynb

Add notebook for editing published variable definition

Notebook: edit published

---

demo/variable_definitions/opprette_gyldighetsperiode.ipynb

Add notebook for creating new validity period for published variable definition

Notebook: create validity period

---

demo/variable_definitions/sjekk_kortnavn.ipynb
demo/variable_definitions/sjekk_om_kortnavn_er_ledig.ipynb

Simple notebook for checking short name availability

Notebook check shortname

---

demo/variable_definitions/slette_utkast.ipynb

Notebook for deleting draft by short name

Notebook: delete draft

---

demo/variable_definitions/lese_en_variabeldefinisjon.ipynb
demo/variable_definitions/lese_variabel_definisjoner.ipynb
demo/variable_definitions/migrere_variabel_definisjon.ipynb
demo/variable_definitions/opprette_gyldighetsperiode.ipynb
demo/variable_definitions/publisere_variabel_definisjon.ipynb
demo/variable_definitions/redigere_publisert_variabel_definisjon.ipynb
demo/variable_definitions/redigere_utkast.ipynb

Strip input variables to avoid errors caused by whitespace

strip input in Notebooks

---

demo/variable_definitions/opprette_gyldighetsperiode.ipynb

Requested by user test manager

Update notebook intro

---

src/dapla_metadata/variable_definitions/variable_definition.py
tests/variable_definitions/conftest.py
tests/variable_definitions/test_variable_definition.py
tests/variable_definitions/vardef_client/api/test_happy_path.py

- Updates the model instance when updating a variabel in vardef

Update the pydantic model from file

---

src/dapla_metadata/standards/name_validator.py
src/dapla_metadata/standards/standard_validators.py
tests/standards/test_name_validator.py

- One separate validator class for `BucketNameValidator` 
- Handle bucket does not exist

Validation for file path and bucket

---

src/dapla_metadata/datasets/dataset_parser.py
src/dapla_metadata/standards/name_validator.py
src/dapla_metadata/standards/utils/constants.py
tests/standards/test_check_naming_standard.py

- Validate all supported dataset files
- Include results for ignored files as well
- Improve test
- Factor check for file type into `validate_file`

Include result for ignored files

---

demo/standards/navnestandard.ipynb

- **correct header demo**
- **correct grammar**

Fix notebook grammar

---

src/dapla_metadata/datasets/core.py

Some changes to make _check_dataset_consisteny work as expected

Reorganized logic

---

src/dapla_metadata/datasets/core.py

- Using the new Datadoc model for the Pseudonomized personal data

Updating to use the new model

---

demo/variable_definitions/migrer_variabeldefinisjoner.ipynb

Notebook example for migrating multiple variable definitions

Migration notebook

---

pyproject.toml
src/dapla_metadata/variable_definitions/_utils/config.py
tests/variable_definitions/test_config.py

- Update to include Vardef prod url

Add Vardef prod url

---

src/dapla_metadata/datasets/utility/utils.py
src/dapla_metadata/variable_definitions/variable_definition.py
tests/variable_definitions/resources/variable_definition_editing_files/variable_definition_var_test_wypvb3wd_2025-09-18T14-19-28.yaml
tests/variable_definitions/test_variable_definition.py

- Prevents creation of useless patches
- Will error if user attempts to only change short_name

Only allow creating patch if changes are made

---

uv.lock

Fix issue with documentation failing

---

src/dapla_metadata/datasets/utility/urn.py
tests/datasets/test_urn.py

All None values produced warnings, this PR fixes that.

Don't warn on URI is None under URN conversion

---

src/dapla_metadata/datasets/core.py
src/dapla_metadata/datasets/utility/urn.py
tests/datasets/test_urn.py

- **URN error log has more context**
- **Generalize conversion function to avoid code duplication**
- **Don't error on correct URN format**

Improve error messages on URN conversion
