statisticsnorway/dapla-toolbelt-metadata

- src/dapla_metadata/datasets/dapla_dataset_path_info.py
- tests/datasets/test_dapla_dataset_path_info.py
Relevant specification: https://statistics-norway.atlassian.net/wiki/spaces/MPD/pages/2953084957/Standardformater#SSBs-egne-dato-formater-for-periodeinndeling-av-et-%C3%A5r
These changes are made following a decision on naming standard updates on 30.09.2024. Changes to documentation in the Dapla Manual and on Confluence to come.
Changes are additive so will not break any existing files or workflows.
- **Add test for klargjorte-data format**
- **Add failing test cases with dash in SSB date formats**
- **Also accept dash in SSB format date strings**
> Also accept dash in SSB format date strings

- src/dapla_metadata/variable_definitions/exceptions.py
- src/dapla_metadata/variable_definitions/vardef.py
- tests/utils/constants.py
- tests/variable_definitions/vardef_client/test_exceptions.py
- Format list of violations as string separated by new line for each violation
- User who needs to access the original response format can use "response_body"
> Format exception response

- src/dapla_metadata/variable_definitions/__init__.py
- src/dapla_metadata/variable_definitions/vardef.py
- src/dapla_metadata/variable_definitions/variable_definition.py
- tests/variable_definitions/test_vardef.py
- tests/variable_definitions/test_variable_definition.py
This overrides the python ["dunder method" `__str__`](https://docs.python.org/3/reference/datamodel.html#object.__str__) to provide a much more readable representation of a Variable Definition.
```
id='wypvb3wd' patch_id=1 name=LanguageStringType(nb='Landbakgrunn', nn='Landbakgrunn', en='Country Background') short_name='landbak' definition=LanguageStringType(nb='For personer født i utlandet, er dette (med noen få unntak) eget fødeland. For personer født i Norge er det foreldrenes fødeland. I de tilfeller der foreldrene har ulikt fødeland, er det morens fødeland som blir valgt. Hvis ikke personen selv eller noen av foreldrene er utenlandsfødt, hentes landbakgrunn fra de første utenlandsfødte en treffer på i rekkefølgen mormor, morfar, farmor eller farfar.', nn='For personar fødd i …
```
> Response models print as indented JSON

- src/dapla_metadata/variable_definitions/generated/.openapi-generator-ignore
- src/dapla_metadata/variable_definitions/generated/.openapi-generator/FILES
- src/dapla_metadata/variable_definitions/generated/vardef_client/api/patches_api.py
- src/dapla_metadata/variable_definitions/generated/vardef_client/api/validity_periods_api.py
- src/dapla_metadata/variable_definitions/generated/vardef_client/models/variable_status.py
- tests/utils/constants.py
- tests/variable_definitions/conftest.py
- tests/variable_definitions/resources/variable-definitions-0.1.yml
- tests/variable_definitions/test_vardef.py
- **More error examples in OpenAPI definition**
- **Tests for 404 for more methods**
> Tests for 404 for more methods

- .github/workflows/tests.yml
Github actions job for Sonar cloud seems to be deprecated now
ref: https://github.com/SonarSource/sonarcloud-github-action
ref: https://docs.sonarsource.com/sonarqube-cloud/enriching/test-coverage/python-test-coverage/
> Update sonar cloud job

- .vscode/settings.json
- demo/variable_definitions/vardef_demo.ipynb
- src/dapla_metadata/variable_definitions/__init__.py
The import statements in the demo notebook are now simplified to be as shown below.
Models may then be accessed as shown here:
> Simplify imports in vardef demo notebook

- pyproject.toml
- Seems like this is needed to use the final version of the package in datadoc-editor
> Add pytyped file

- src/dapla_metadata/variable_definitions/config.py
- src/dapla_metadata/variable_definitions/utils/variable_definition_files.py
- src/dapla_metadata/variable_definitions/vardef.py
- tests/variable_definitions/conftest.py
- tests/variable_definitions/test_config.py
- tests/variable_definitions/test_template.py
- tests/variable_definitions/test_vardef_write_template.py
- tests/variable_definitions/test_variable_definition_files.py
- Read env value "WORKSPACE_DIR" from config.  This method can return `None` if no value.
- Handle the potential null value when determining workspace directory:
- Should be a `VardefFileError` because user can choose to provide a custom path or check/correct
> Read workspace dir from config

- src/dapla_metadata/variable_definitions/utils/variable_definition_files.py
Suppress warnings like the following when writing a variable to file
```
my_draft = Vardef.write_variable_to_file(short_name="arbkonfl")
Warning: Pydantic serializer warnings:
Expected `LanguageStringType` but got `dict` with value `{'nb': 'Tapte arbeidsdage...n': 'Working days lost'}` - serialized value may not be as expected
Expected `LanguageStringType` but got `dict` with value `{'nb': 'Varigheten av en ...es, not calendar days.'}` - serialized value may not be as expected
Expected `Owner` but got `dict` with value `{'team': 'dapla-felles', ...pla-felles-developers']}` - serialized value may not be as expected
Expected `Contact` but got `dict` with value `{'title': {'nb': 'generer...': 'generert@epost.com'}` - serialized value may not be as expected, Category: UserWarning, Filename: …
```
> Suppress Pydantic warnings

- src/dapla_metadata/variable_definitions/utils/constants.py
- src/dapla_metadata/variable_definitions/utils/variable_definition_files.py
Include information whether field is required or not.
Use symbols to signal importance.
> Add required/optional to field descriptions

- src/dapla_metadata/variable_definitions/vardef.py
- tests/variable_definitions/test_vardef.py
There has been mentioned the need for checking if a short name already exists when owners discussing/decide short names. Especially when migrating from Vardok.
> add method check if short name exists

- sonar-project.properties
This was set under settings Sonar cloud, but was broken when file paths changed
Add to file because it is easier to keep up with changes from the code
There are three possible settings (sonar.coverage.exclusions, sonar.cpd.exclusions and sonar.exclusions)
sonar.exclusions should exclude generated files both from code coverage and duplication
> add exclusion for generated files sonar cloud

- demo/variable_definitions/redigere_utkast.ipynb
Fixing so that a variable definition with status draft can be updated from the same file more than once
> Fixing bug causing file path to be lost

- src/dapla_metadata/datasets/dapla_dataset_path_info.py
- src/dapla_metadata/standards/name_validator.py
- src/dapla_metadata/standards/standard_validators.py
- src/dapla_metadata/standards/utils/constants.py
- tests/standards/test_name_validator.py
- tests/standards/test_standards.py
Assuming https://manual.dapla.ssb.no/statistikkere/navnestandard.html#partisjonerte-data is correct:
- Trim the file path for key/value parts and the file suffix part in `DaplaDatasetPathInfo` 
- Valid symbol is now also "="
- Separate class for `PartitionedDataValidator`, but for now it is only check for invalid symbols which differ from other validations. But it could maybe be other unique partitioned file path checks
> Validate partitioned dataset paths

- pyproject.toml
- src/dapla_metadata/datasets/dataset_parser.py
- tests/datasets/test_dataset_parser.py
Adding:
- string[pyarrow]
- large_string
- timestamp[s]
- timestamp[ms]
- date32[day]
- datetime64[s]
- datetime64[ms]
Resolves #181
> Add concrete data types to dataset parser

- schemas/jsonschema/complete-response-schema.json
- src/dapla_metadata/variable_definitions/resources/vardef_model_descriptions_nb.yaml
- tests/variable_definitions/resources/variable_definition_editing_files/variable_definition_arbkonfl_qSDlxNVO_2025-03-04T09-46-14.yaml
- To assist with correctly editing variable definition files, we provide
a json-schema.
- This may be used in VS Code and other text editors to provide
information to the user about the meaning of fields and provide feedback
when a value is incorrect.
- A usage example of this may be explored in `tests/variable_definitions/resources/variable_definition_editing_files/variable_definition_arbkonfl_qSDlxNVO_2025-03-04T09-46-14.yaml`
- In future work, we will configure a service such that this is automatically connected to users' files.
> json-schema for variable definition yaml files

- .github/workflows/tests.yml
- noxfile.py
- poetry.lock
- pyproject.toml
- src/dapla_metadata/datasets/code_list.py
- src/dapla_metadata/datasets/model_backwards_compatibility.py
- src/dapla_metadata/datasets/model_validation.py
- src/dapla_metadata/datasets/utility/utils.py
- src/dapla_metadata/variable_definitions/_generated/vardef_client/exceptions.py
- tests/datasets/conftest.py
- **Set 3.10 as minimum Python version**
- **Nox runs on 3.10 as well**
- **Run tests GHA on 3.10**
- **Release v0.6.2**
> Reenable Python 3.10 support

- demo/variable_definitions/publisere_variabel_definisjon_eksternt.ipynb
- demo/variable_definitions/publisere_variabel_definisjon_internt.ipynb
- One notebook for publish internal for variable definitions with status `DRAFT`
- One notebook for publish external for variable definitions with either status `DRAFT` or `PUBLISHED_INTERNAL`
- Add user feedback to confirm the selected variable definition before proceeding with publication as requested by users
Reviewer should confirm that all rules regarding publishing are correct and the text is not ambiguous
> Separate publish variable definitions notebook

- .gitignore
Based on the reference gitignore file here: https://github.com/statisticsnorway/kvakk-git-tools/blob/main/kvakk_git_tools/recommended/gitignore we add all the missing lines.
This will still fail when used with `ssb-project build` because ssb-project does not fetch the reference gitignore file, but holds its own outdated copy. There is currently work underway to fix this and after that is complete this repo should pass the validation.
> Update .gitignore to match kvakk standard

- src/dapla_metadata/variable_definitions/_utils/files.py
Accessing model_fields from instance is deprecated in Pydantic v3.
Instead use instance to access the class.
> Fix deprecated accessing attribute on instance

- src/dapla_metadata/standards/name_validator.py
- src/dapla_metadata/standards/utils/constants.py
Fix reported issue by users
- Update violation message to reflect the naming standard rule which allow omitting version on newest file
- Change from linking to filename chapter to versioning chapter
- Adjust percentage result in attempt to reflect the possibility for "success" also with score under 100%
> Fix misleading name validation result

- src/dapla_metadata/variable_definitions/_utils/constants.py
- src/dapla_metadata/variable_definitions/_utils/files.py
- src/dapla_metadata/variable_definitions/_utils/template_files.py
- src/dapla_metadata/variable_definitions/_utils/variable_definition_files.py
- src/dapla_metadata/variable_definitions/resources/vardef_model_descriptions_nb.yaml
- tests/variable_definitions/test_variable_definition.py
- tests/variable_definitions/test_variable_definition_files.py
**Improve user experience yaml file**
Use block type on multi language fields:
- Can save special characters like ":"
- Save newlines and indentation etc
- Strip leading/trailing whitespace
Reduce use of placeholder text template:
- Decrease risk for saving placeholder text
- Examples are preserved and better for demonstrating usage/type/values etc
Comments:
- Distinguish more clearly between explanation and example
Yaml syntax highlighting will not be fully correct, but the values are saved correctly:
ref: https://statistics-norway.atlassian.net/browse/DPMETA-846
> Improve template file

- .vscode/settings.json
- poetry.lock
- pyproject.toml
This takes advantage of the more globally compatible format as defined in [PEP 621](https://peps.python.org/pep-0621/) and detailed here https://python-poetry.org/blog/announcing-poetry-2.0.0 .
It also releases downstream projects from the upper Python version bound by specifying `requires-python = '>=3.10'` since this is no longer required or recommended! ref https://packaging.python.org/en/latest/specifications/core-metadata/#core-metadata-requires-python
This adds more VSCode config as well, to help with getting formatting right in the IDE. The config expected the following extensions to be installed:
* https://marketplace.visualstudio.com/items/?itemName=tamasfe.even-better-toml
* https://marketplace.visualstudio.com/items/?itemName=ms-python.mypy-type-checker
* …
> Migrate `pyproject.toml` to Poetry v2 syntax

- src/dapla_metadata/variable_definitions/_utils/files.py
- src/dapla_metadata/variable_definitions/resources/vardef_model_descriptions_nb.yaml
Setting either "Obligatorisk felt" or "Valgfritt felt" in Yaml files was based on field info `is_required`.
But this value could be wrong for fields with default value.
- Set `variable_status` as "Obligatorisk felt"
- Remove requirement info entirely for machine generated fields 
Also:
- Set yaml width to "4096" to prevent wrapping lines
- Adjust descriptions
> Field requirement status in yaml

- vardef-maintenance/vardef_client_init.sh
If a Dapla Lab service is paused and then resumed, the script would run again. This is unnecessary and has potential to overwrite user data. We avoid this by checking whether the directory exists before continuing.
> Vardef-forvaltning script: Don't run multiple times

- src/dapla_metadata/datasets/statistic_subject_mapping.py
- tests/datasets/resources/statistical_subject_structure/extract_secondary_subject.xml
- tests/datasets/test_statistic_subject_mapping.py
Reported by @aosthus 
Current Datadoc does not take into account the "isPrimaerPlassering" flag in th XML from Mimir.
This places the Shortname in the wrong Subjects when the Shortname is in multiple Subjects.
This PR just filters down to the first true "primary placement", after a check all shortnames have at least on primary placement, but some have multiple.
> Only consider primary placement when mapping from a specific statistic to a subject field

- .vscode/settings.json
- noxfile.py
- poetry.lock
- pyproject.toml
- src/dapla_metadata/__init__.py
- src/dapla_metadata/datasets/core.py
- src/dapla_metadata/datasets/dapla_dataset_path_info.py
- src/dapla_metadata/datasets/dataset_parser.py
- src/dapla_metadata/datasets/utility/constants.py
- src/dapla_metadata/datasets/utility/utils.py
- tests/datasets/constants.py
- tests/datasets/resources/existing_metadata_file/person_testdata_p2020-12-31_p2020-12-31_v1__DOC.json
- tests/datasets/test_dapla_dataset_path_info.py
- tests/datasets/test_datadoc_metadata.py
- tests/datasets/test_dataset_parser.py
- tests/datasets/test_validators.py
This will allow validating that completed datadoc metadata documents contain all of the required metadata.
- Implemented as a flag on Datadoc class
- Update to ssb-datadoc-model v6.1.0
- Explicitly name models `all_optional_model` and `required_model`
> Support validation of required fields on existing metadata document

- src/dapla_metadata/datasets/core.py
- tests/datasets/test_datadoc_metadata.py
- Method that allows for the removal of a pseudo variable
- When adding a pseudo variable is_personal_data is set to PSEUDONYMISED_ENCRYPTED_PERSONAL_DATA
- When removing a pseudo variable is_personal_data is set to NON_PSEUDONYMISED_ENCRYPTED_PERSONAL_DATA
> Remove a pseudo variable

- src/dapla_metadata/variable_definitions/_utils/constants.py
- src/dapla_metadata/variable_definitions/exceptions.py
- src/dapla_metadata/variable_definitions/variable_definition.py
- tests/variable_definitions/test_variable_definition.py
Ref: https://statistics-norway.atlassian.net/browse/DPMETA-937
Introduce a custom exception `PublishingBlockedError` along with a decorator (`publishing_blocked_error_handler`) to temporarily block publishing of variable definitions in the production environment.
The decorator should be applied to publish-related methods. It blocks publishing when the `variable_status` is set to `PUBLISHED_INTERNAL` or `PUBLISHED_EXTERNAL`.
It allows `DRAFT` status to pass through in `update_draft`, so other modifications to a draft are not unintentionally blocked.
The decorator is also applied to higher-level methods that call `update_draft`, to ensure the publishing block is enforced immediately—before any further processing or validation.
> Disable publish variable definitions in production environment

- demo/variable_definitions/reserver_kortnavn.ipynb
- src/dapla_metadata/variable_definitions/__init__.py
- src/dapla_metadata/variable_definitions/_utils/constants.py
- src/dapla_metadata/variable_definitions/_utils/template_files.py
- tests/variable_definitions/conftest.py
- Users can supply a list of `short_name` which are then used to create draft variable definitions with placeholder values.
- It is not possible to publish the drafts without first editing them.
> Notebook to reserve short names

- vardef-maintenance/vardef_client_init.sh
- Currently ssb-project build --no-verify still runs the git verification step
- This fix passes n to that step so that the kernel will be created
> Fix ssb project build not finishing
